### ISSUE TITLE
Use Lego.raw with Arrays

### ISSUE THREAD

**Issue by tamagokun** [martijndeh/lego#1]
When doing a query that has both dynamic values and dynamic column names, things get a bit hairy.

Here's an example

```js
const params = {
  age: 10,
  name: 'Bob'
}

await Lego.sql `UPDATE users SET ${Object.keys(params).map(key => Lego.sql `${Lego.raw(key)} = ${params[key]}`)} WHERE id = ${id}`
```

This does not appear to work, though perhaps I am just not using the correct combination of `Lego.sql` and `Lego.raw`

**Comment by martijndeh** [comment]
You are doing the correct thing, but it seems you're seeing a bug here.

I've written a test and fixed the issue. There was a mismatch in the order of the parameters (the last parameter).

Can you please confirm? The fix is published in version 2.4.2!
